### ISSUE TITLE
(feat): Namespaced ClusterProfile resources

### ISSUE THREAD

**Issue by lukasmrtvy** [projectsveltos/addon-controller#396]
**Is your feature request related to a problem? Please describe.**
CAPI `Cluster` resource is namespaced while `ClusterProfile` isn't, thus `ClusterProfile` has different ownership than `Cluster`, usually consumers are not allowed to deploy namespace-less resources ( `ClusterProfile` ) into clusters where Sveltos and CAPI controllers are running. Namespaced `ClusterProfile` is a life-improving change that will improve the experience in situations like this.

**Describe the solution you'd like**
Namespaced `ClusterProfile` resource, probably just `Profile` which can match only:
- clusters in the same namespace
- resources in the same namespace

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by prometherion** [comment]
I like this feature enhancement since it makes total sense!

@gianlucam76 any expectation in getting this available in v0.21.0, along with an ETA?

**Comment by gianlucam76** [comment]
Thank you @prometherion good to hear. 

This will be available in v0.21.0, which should be released next week.

**Comment by gianlucam76** [comment]
Feature will be available in v0.21.0
