### ISSUE TITLE
BUG: lagged addons delivery

### ISSUE THREAD

**Issue by prometherion** [projectsveltos/addon-controller#415]
# Problem Description

1. Create a `{Cluster}Profile`
2. Deploy a Cluster (Cluster API or SveltosCluster)
3. Wait up to 10 minutes before getting the addon delivered

# System Information

CLUSTERAPI VERSION: `v1.6.0`
SVELTOS VERSION: `v1.21.0`
KUBERNETES VERSION: `v1.27.3`

# Logs

N.R.

**Comment by gianlucam76** [comment]
Thank you!

**Comment by gianlucam76** [comment]
Rebuilt image v0.21.0
