### ISSUE TITLE
BUG: ClusterSummary is not cleaned-up upon Cluster deletion

### ISSUE THREAD

**Issue by prometherion** [projectsveltos/addon-controller#416]
# Problem Description

1. Define a `{Cluster}Profile`
2. Create several clusters
3. Thanks to labels, wait for addons being deployed
4. Delete one of the clusters
5. Check the deployed cluster still has a `ClusterSummary`

tl;dr; the `ClusterSummary` must be deleted as well upon the referencing cluster is deleted too.

# System Information

CLUSTERAPI VERSION: `v1.6.0`
SVELTOS VERSION: ` v1.21.0`
KUBERNETES VERSION: ` v1.27.3`

# Logs

N.R.

**Comment by gianlucam76** [comment]
Thank you!
