### ISSUE TITLE
Can cluster profile deploy a kustomization ref to only a set number of clusters in a cluster label

### ISSUE THREAD

**Issue by ramekris3163** [projectsveltos/addon-controller#451]
In the example provided for deploying a kutomization, https://projectsveltos.github.io/sveltos/addons/kustomize/ it will deploy the app, config map and secrets to all the clusters with the label env=fv .

In case i have two clusters with label env=fv, it will deploy it to both the clusters.

Does cluster profile have any mechanism to restrict the number of cluster to which the kustomization is deployed in when there are multiple clusters in a label?

ex:

i have two custers with label prod, 

kubectl get sveltosclusters -n projectsveltos --show-labels
NAME                         READY   VERSION   LABELS
clusterapi-workload-dev      true    v1.27.1   env=dev,sveltos-agent=present
clusterapi-workload-prod     true    v1.27.1   env=prod,sveltos-agent=present
clusterapi-workload-prod-1   true    v1.27.1   env=prod,sveltos-agent=present

When i deploy the sample kustomization ref, it gets deployed to both the prod labled clusters:

sveltosctl/bin/sveltosctl show addons
+-------------------------------------------+-----------------+-------------+----------------------+---------+-------------------------------+-----------------------------------+
|                  CLUSTER                  |  RESOURCE TYPE  |  NAMESPACE  |         NAME         | VERSION |             TIME              |             PROFILES              |
+-------------------------------------------+-----------------+-------------+----------------------+---------+-------------------------------+-----------------------------------+
| projectsveltos/clusterapi-workload-dev    | helm chart      | vela-system | kubevela-core-latest | 1.9.9   | 2024-02-08 15:49:19 -0500 EST | ClusterProfile/kubevela-core      |
| projectsveltos/clusterapi-workload-prod   | helm chart      | vela-system | kubevela-core-latest | 1.9.6   | 2024-02-08 15:52:03 -0500 EST | ClusterProfile/kubevela-core-prod |
| projectsveltos/clusterapi-workload-prod   | apps:Deployment | eng         | the-deployment       | N/A     | 2024-02-08 17:31:56 -0500 EST | ClusterProfile/flux-system        |
| projectsveltos/clusterapi-workload-prod   | :Service        | eng         | the-service          | N/A     | 2024-02-08 17:31:56 -0500 EST | ClusterProfile/flux-system        |
| projectsveltos/clusterapi-workload-prod   | :ConfigMap      | eng         | the-map              | N/A     | 2024-02-08 17:31:56 -0500 EST | ClusterProfile/flux-system        |
| projectsveltos/clusterapi-workload-prod-1 | helm chart      | vela-system | kubevela-core-latest | 1.9.6   | 2024-02-08 17:01:49 -0500 EST | ClusterProfile/kubevela-core-prod |
| projectsveltos/clusterapi-workload-prod-1 | apps:Deployment | eng         | the-deployment       | N/A     | 2024-02-08 17:31:56 -0500 EST | ClusterProfile/flux-system        |
| projectsveltos/clusterapi-workload-prod-1 | :Service        | eng         | the-service          | N/A     | 2024-02-08 17:31:57 -0500 EST | ClusterProfile/flux-system        |
| projectsveltos/clusterapi-workload-prod-1 | :ConfigMap      | eng         | the-map              | N/A     | 2024-02-08 17:31:57 -0500 EST | ClusterProfile/flux-system        |
+-------------------------------------------+-----------------+-------------+----------------------+---------+-------------------------------+-----------------------------------+

Can we restrict it to deploy the cluster to only one of the prod clusters.

**Comment by gianlucam76** [comment]
Thank you @ramekris3163 

Have you considered using Profile? Profiles are like ClusterProfile but namespace scoped.

So if you have:
- cluster1 (label env=fv) in namespace foo 
- cluster2 (label env=fv) in namespace bar

You can create this profile in namespace foo and Sveltos will deploy only in cluster1

```yaml
apiVersion: config.projectsveltos.io/v1alpha1
kind: Profile
metadata:
  name: flux-system
  namespace: foo
spec:
  clusterSelector: env=fv
  syncMode: Continuous
  kustomizationRefs:
  - namespace: flux-system
    name: flux-system
    kind: GitRepository
    path: ./helloWorld/
    targetNamespace: eng
```

**Comment by gianlucam76** [comment]
Another option available, is to set Spec.Paused to true.

So assuming you have two clusters:

- cluster1 (labels: env=dev)
- cluster2(labels: env=dev)

A single ClusterProfile can be created with **clusterSelector: env=dev**,  so it matches both.

Assuming we want Sveltos to reconcile only cluster1 (and not cluster2), set **cluster2.Spec.Paused = true**

**Sveltos won't reconcile any cluster set to Paused.**

In order for Sveltos to start reconciling add-ons and applications on cluster2,  reset cluster2.Spec.Paused = false

**Comment by gianlucam76** [comment]
ClusterSet/Set might also help.

https://github.com/projectsveltos/addon-controller/commit/b842ac302cf671b5ef2e3262e7dd4d5507763eac

**Comment by gianlucam76** [comment]
@ramekris3163 are you OK if we close this now that ClusterSet/Set have been introduced?
