### ISSUE TITLE
BUG: Value changes not reconciled/redeployed

### ISSUE THREAD

**Issue by Uva-Vj** [projectsveltos/addon-controller#499]
# Problem Description

Any changes to values of helm charts defined in ClusterProfile doesn’t reconcile/redeploy K8s controllers. Is this expected behavior?

For example, When I apply the below values to the already defined nginx helm chart with no values in ClusterProfile, the nginx deployment doesn’t get redeployed. The addon-controller log shows `added to result with err cannot re-use a name that is still in use`. Does this mean the releaseName should be updated with every value change? If I change the releaseName
/chartVersion reconcile happens and new nginx pods get deployed without any issue.

Seems similar to https://github.com/projectsveltos/addon-controller/issues/93 but for non-templated values.

New Values:
```
    values: |-
      containerPorts:
        http: 8190
```

ClusterProfile.yml
```
apiVersion: config.projectsveltos.io/v1alpha1
kind: ClusterProfile
metadata:
  name: nginx
spec:
  clusterSelector: cluster=vcenter1-lab
  syncMode: Continuous
  helmCharts:
  - repositoryURL:    artifactory/kubernetes-helm
    repositoryName:   kubernetes-helm
    chartName:        kubernetes-helm/nginx
    chartVersion:     13.1.7
    releaseName:      nginx-sveltos
    releaseNamespace: k8s-admin
    helmChartAction:  Install
```

# System Information

CLUSTERAPI VERSION: `v1.6.1`
SVELTOS VERSION: `v0.26.0`
KUBERNETES VERSION: `v1.29.0 `

# Logs

```
│ I0405 07:35:07.142197       1 worker.go:238] "added to result with err cannot re-use a name that is still in use" logger="deployer" worker="6" key="default:::vcenter1-lab:::Capi:::nginx-capi-vcenter1-lab:::Helm:::false"
```

**Comment by gianlucam76** [comment]
Thank you @Uva-Vj  for filing this issue. I will look into and update.

**Comment by gianlucam76** [comment]
The main issue I see is that once an helm chart is installed, changing values section has no effect. Sveltos checks current installed version and the version to be installed. Given those are same it thinks that is a no-op. 

I will fix this behaviour in next release (v0.28.0)

**Comment by gianlucam76** [comment]
This will be in v0.28.0 which should be released by end of this week.

**Comment by gianlucam76** [comment]
Release v0.28.0 is out and contains fix for this https://github.com/orgs/projectsveltos/discussions/510

@Uva-Vj I am closing this. But please let me know if you still see issues. 

Thank you again for the detailed description. Really appreciated it.
