### ISSUE TITLE
Drift detection: ignore certain fields when resources are deployed with ContinuousWithDriftDetection

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/addon-controller#585]
**Is your feature request related to a problem? Please describe.**
Consider the case where a Deployment is deployed using Sveltos along with Autoscaler. 
In this scenario, Deployment _spec.replicas_ field will be modified by Autoscaler.

Ideally we want Sveltos to detect a configuration drift (a change in the Deployment). But we don't want Sveltos to react to _spec.replicas_ be modified (as that is expected to happen and it is not a configuration drift)

**Comment by oliverbaehler** [comment]
@gianlucam76 could you implement this? The code base is too complex for me tbh :D

**Comment by gianlucam76** [comment]
Available in release v0.36.0
