### ISSUE TITLE
BUG: addons does not get installed on cluster, if a cluster is deleted and recreated with the same name

### ISSUE THREAD

**Issue by psarwate** [projectsveltos/addon-controller#711]
Addon does not get into provisioning state on the CAPI cluster, if we delete the older workload cluster and recreate new workload cluster with the same name.

 
Steps to repro:

- Create CAPI cluster, and wait for cluster to go into running state
- Wait for all addons to go into provisioned state
- Delete the older openstack cluster, and ensure all clustersummary objects get deleted as well.
- Recreate the CAPI cluster with same cluster name and this time addons don't come up on the cluster

We observer below errors in the addon controller:

> I0902 09:43:19.973879       1 clustersummary_controller.go:527] "no policy status. Do not reconcile this" controller="clustersummary" controllerGroup="[config.projectsveltos.io](http://config.projectsveltos.io/)" controllerKind="ClusterSummary" ClusterSummary="org-pmaru/core-addons-capi-capi3" namespace="testns" name="core-addons-capi-capi3" reconcileID="dd0564e6-4d5c-4249-8dbd-8521d33373f6" clusternamespace="testns" clustername=“capi3"
> 
> E0902 09:43:19.973912       1 clustersummary_controller.go:377] "**failed to deploy" err="cleanup of Helm still in progress**. Wait before redeploying" controller="clustersummary" controllerGroup="[config.projectsveltos.io](http://config.projectsveltos.io/)" controllerKind="ClusterSummary" ClusterSummary="testns/core-addons-capi-capi3" namespace="testns" name="core-addons-capi-capi3" reconcileID="dd0564e6-4d5c-4249-8dbd-8521d33373f6”

I can add more details if needed. But above steps worked for us everytime and the error in the controller is also consistently seen.

Version: 0.35.0

**Comment by psarwate** [comment]
Thanks for fixing this @gianlucam76. Is this planned for tag 0.38.4?

**Comment by OmkarDeshpande7** [comment]
@gianlucam76 Thanks for the quick fix and super fast release `v0.38.4`. I am seeing chart version `0.38.4` is not yet available at `https://projectsveltos.github.io/helm-charts`. Can you confirm if that will be uploaded soon?

**Comment by gianlucam76** [comment]
Hi @OmkarDeshpande7 I am doing the release now. I will release it in 30 minutes or so

**Comment by gianlucam76** [comment]
released v0.38.4
