### ISSUE TITLE
Feature Request: Register Cluster with dynamic secret key

### ISSUE THREAD

**Issue by JonnyBDev** [projectsveltos/addon-controller#743]
**Is your feature request related to a problem? Please describe.**
The option to configure a [Sveltos Cluster programmatically](https://projectsveltos.github.io/sveltos/register/register-cluster/#configuring-sveltos-clusters-programmatically) is already given. In the Custom Resource you can [define the name of the kubeconfig secret](https://github.com/projectsveltos/libsveltos/blob/main/api/v1alpha1/sveltoscluster_type.go#L76). Controlplane Management Tools like Kamaji are creating secrets with a unique name (clustername-admin-kubeconfig). This is no problem, because you can define the secretname. The problem is one level deeper.

Kamaji for example is setting the keys `admin.conf` and `super-admin.conf`. To use the kubeconfig I'd have to duplicate the secret and change one key to `kubeconfig` as required by Sveltos. This could bring up some implications for example if Kamaji is renewing the secret every year.

**Describe the solution you'd like**
A good solution would be to be able to specify the actual key in the secret which should be used. This way, at least if used in combination with Kamaji, no further changes are needed and the secret is always up to date.

**Describe alternatives you've considered**
Duplicating the secret is an alternative, but you'd have to monitor for kubeconfig changes from Kamaji e.g. a cert rotation.

**Additional context**
![image](https://github.com/user-attachments/assets/669431aa-bed0-45d7-ae4f-4104ac8a59e6)

**Comment by gianlucam76** [comment]
Thanks @JonnyBDev 

It makes sense. I will make that configurable in the SveltosSecret. Thank you

**Comment by gianlucam76** [comment]
Hi @JonnyBDev I have pushed it [here](https://github.com/projectsveltos/libsveltos/pull/372)

I am already in the middle of release v0.41.0. So this will come in v0.41.1 (either Monday or Tuesday)
