### ISSUE TITLE
BUG: Failed to get user from token in Dashboard

### ISSUE THREAD

**Issue by emreberber** [projectsveltos/addon-controller#792]
### Problem Description

Hello. I created Token with Platform-Admin, but I get an error on the login screen.

[Platform Administrator Example](https://projectsveltos.github.io/sveltos/getting_started/install/dashboard/)

### System Information

SVELTOS VERSION: ` 0.41.1 `
KUBERNETES VERSION: ` 1.27.4`

### Logs

```
(http.go:519] "failed to get user from token: the server could not find the requested resource" logger="gin")
```

<img src="https://github.com/user-attachments/assets/fb1e62d3-3237-4905-b6a8-55bd861d7cd7" alt="Screenshot" style="height:10px;">

**Comment by gianlucam76** [comment]
Thanks @emreberber 

Can you please list the steps you used to create the token? Thank you

**Comment by gianlucam76** [comment]
Thank you. Giving a try now. Thanks

**Comment by emreberber** [comment]
I tried exactly these steps but I get the same error again.

I am using Kind.

```
k3d cluster create projectsveltos-cluster-02 \                                                                                                                                        
    --agents 2 --servers 1  \
    --image rancher/k3s:v1.27.4-k3s1
```

```
+----------------------------------------+-----------------+---------------------------------------------------------+
| dashboard-54c6777f9c-9tnz5             | dashboard       | docker.io/projectsveltos/dashboard:v0.41.1              |
+----------------------------------------+-----------------+---------------------------------------------------------+
| ui-backend-manager-596f8bddf6-82qg7    | manager         | projectsveltos/ui-backend:v0.41.1                       |
+----------------------------------------+-----------------+---------------------------------------------------------+
```

**Comment by gianlucam76** [comment]
Thanks. Trying that as well. I assume you are doing a port-forward of the dashboard service

**Comment by emreberber** [comment]
Yes, that's exactly it.

```
kubectl port-forward svc/dashboard -n projectsveltos 8080:80
```

**Comment by gianlucam76** [comment]
I was able to repro. The version v1.27 does not support this authentication. 

I tried with 

```
k3d cluster create projectsveltos-cluster-03 \               
    --agents 2 --servers 1  \
    --image rancher/k3s:v1.29.10-k3s1
```

and following all steps above, it worked.

**Comment by gianlucam76** [comment]
v1.28.0 seems to be the first Kubernetes verision with SelfSubjectReview

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md

```
The SelfSubjectReview API is promoted to authentication.k8s.io/v1 and the kubectl auth whoami command is GA. (https://github.com/kubernetes/kubernetes/pull/117713, [@nabokihms](https://github.com/nabokihms)) [SIG API Machinery, Architecture, Auth, CLI and Testing]
```

**Comment by gianlucam76** [comment]
I will use this bug to add a note on documentation, Dashboard requires  v1.28.0 or newer release.

**Comment by emreberber** [comment]
Great work 🚀  Thanks

**Comment by gianlucam76** [comment]
[Note](https://github.com/projectsveltos/sveltos/pull/385) added
