### ISSUE TITLE
BUG: Secret "webhook-server-cert" not found

### ISSUE THREAD

**Issue by emreberber** [projectsveltos/addon-controller#793]
### Problem Description

conversion-webhook pod stuck in container creating.

I'm trying with install [Centralised Agent Mode](https://projectsveltos.github.io/sveltos/getting_started/install/install/)

### System Information

SVELTOS VERSION: ` 0.41.1 `
KUBERNETES VERSION: `1.27.4`

### Logs

```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    26m                   default-scheduler  Successfully assigned projectsveltos/conversion-webhook-8567997b9b-wrqhw to k3d-projectsveltos-cluster-01-agent-0
  Warning  FailedMount  4m43s (x10 over 24m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
  Warning  FailedMount  26s (x21 over 26m)    kubelet            MountVolume.SetUp failed for volume "cert" : secret "webhook-server-cert" not found
```

**Comment by gianlucam76** [comment]
Thanks @emreberber 

Do you have cert-manager in your management cluster?

**Comment by emreberber** [comment]
I am very sorry, I missed the note about the cert manager. But there is such a situation that when I install cert manager later, Pod still does not start running.

But when I deployed cert manager first and then sveltos in another cluster, there was no problem. 🤔

**Comment by gianlucam76** [comment]
Thank you for verifying this @emreberber 

I am planning on removing the conversion webhook soon since it has already been many releases since we switched from v1alpha1 to v1beta1.

Are you OK if we close this one?

**Comment by emreberber** [comment]
Yeah I'm OK thank you 🙏🏻  We can close this one 👍🏻
